//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalClientes.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalClientes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar mi cuenta.
        /// </summary>
        internal static string AdministrarCuenta {
            get {
                return ResourceManager.GetString("AdministrarCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y contraseña no existen..
        /// </summary>
        internal static string Ce_9999 {
            get {
                return ResourceManager.GetString("Ce_9999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string CerrarSesion {
            get {
                return ResourceManager.GetString("CerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar....
        /// </summary>
        internal static string Cm_Buscador {
            get {
                return ResourceManager.GetString("Cm_Buscador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo es requerido..
        /// </summary>
        internal static string Cm_CampoReq {
            get {
                return ResourceManager.GetString("Cm_CampoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ejemplo@dominio.com.
        /// </summary>
        internal static string CorreoEjemplo {
            get {
                return ResourceManager.GetString("CorreoEjemplo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Completo / Incompleto.
        /// </summary>
        internal static string Das_Completo {
            get {
                return ResourceManager.GetString("Das_Completo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declaración para:.
        /// </summary>
        internal static string Das_DeclaracionPara {
            get {
                return ResourceManager.GetString("Das_DeclaracionPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino:.
        /// </summary>
        internal static string Das_Destino {
            get {
                return ResourceManager.GetString("Das_Destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado del Vuelo.
        /// </summary>
        internal static string Das_EstadoVuelo {
            get {
                return ResourceManager.GetString("Das_EstadoVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas de Vuelo.
        /// </summary>
        internal static string Das_HorasVuelo {
            get {
                return ResourceManager.GetString("Das_HorasVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llegada:.
        /// </summary>
        internal static string Das_Llego {
            get {
                return ResourceManager.GetString("Das_Llego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NM Vuelo.
        /// </summary>
        internal static string Das_NMVuelo {
            get {
                return ResourceManager.GetString("Das_NMVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen:.
        /// </summary>
        internal static string Das_Origen {
            get {
                return ResourceManager.GetString("Das_Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen de la Cuenta.
        /// </summary>
        internal static string Das_ResumenCuenta {
            get {
                return ResourceManager.GetString("Das_ResumenCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo Actual.
        /// </summary>
        internal static string Das_Saldo {
            get {
                return ResourceManager.GetString("Das_Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salida:.
        /// </summary>
        internal static string Das_Salida {
            get {
                return ResourceManager.GetString("Das_Salida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima declaración.
        /// </summary>
        internal static string Das_UltimaDeclaracion {
            get {
                return ResourceManager.GetString("Das_UltimaDeclaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a incluido el vencimiento (+ de 90 días).
        /// </summary>
        internal static string Das_Ven90dias {
            get {
                return ResourceManager.GetString("Das_Ven90dias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vence:.
        /// </summary>
        internal static string Das_Vence {
            get {
                return ResourceManager.GetString("Das_Vence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vuelos.
        /// </summary>
        internal static string Das_Vuelos {
            get {
                return ResourceManager.GetString("Das_Vuelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Lo_Contrasena {
            get {
                return ResourceManager.GetString("Lo_Contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Lo_Correo {
            get {
                return ResourceManager.GetString("Lo_Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string Lo_Ingresar {
            get {
                return ResourceManager.GetString("Lo_Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidó su contraseña?.
        /// </summary>
        internal static string Lo_OlvidoPass {
            get {
                return ResourceManager.GetString("Lo_OlvidoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso.
        /// </summary>
        internal static string Lo_Titulo {
            get {
                return ResourceManager.GetString("Lo_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altitud Máxima:.
        /// </summary>
        internal static string Ta_AltitudMaxima {
            get {
                return ResourceManager.GetString("Ta_AltitudMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año:.
        /// </summary>
        internal static string Ta_Anio {
            get {
                return ResourceManager.GetString("Ta_Anio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacidad.
        /// </summary>
        internal static string Ta_Capacidad {
            get {
                return ResourceManager.GetString("Ta_Capacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dimensiones Exteriores:.
        /// </summary>
        internal static string Ta_DimensionesE {
            get {
                return ResourceManager.GetString("Ta_DimensionesE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dimensiones Interiores:.
        /// </summary>
        internal static string Ta_DimensionesI {
            get {
                return ResourceManager.GetString("Ta_DimensionesI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distancia:.
        /// </summary>
        internal static string Ta_Distancia {
            get {
                return ResourceManager.GetString("Ta_Distancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fabricante:.
        /// </summary>
        internal static string Ta_Fabricante {
            get {
                return ResourceManager.GetString("Ta_Fabricante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustible Max:.
        /// </summary>
        internal static string Ta_MaxCombustible {
            get {
                return ResourceManager.GetString("Ta_MaxCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Combustible Min:.
        /// </summary>
        internal static string Ta_MinCombustible {
            get {
                return ResourceManager.GetString("Ta_MinCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo:.
        /// </summary>
        internal static string Ta_Modelo {
            get {
                return ResourceManager.GetString("Ta_Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro No.:.
        /// </summary>
        internal static string Ta_NoRegistro {
            get {
                return ResourceManager.GetString("Ta_NoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serie No.:.
        /// </summary>
        internal static string Ta_NoSerie {
            get {
                return ResourceManager.GetString("Ta_NoSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasajeros:.
        /// </summary>
        internal static string Ta_Pasajeros {
            get {
                return ResourceManager.GetString("Ta_Pasajeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso:.
        /// </summary>
        internal static string Ta_Peso {
            get {
                return ResourceManager.GetString("Ta_Peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rendimiento:.
        /// </summary>
        internal static string Ta_Rendimiento {
            get {
                return ResourceManager.GetString("Ta_Rendimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aeronave.
        /// </summary>
        internal static string Ta_Subtitulo {
            get {
                return ResourceManager.GetString("Ta_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Combustible:.
        /// </summary>
        internal static string Ta_TipoCombustible {
            get {
                return ResourceManager.GetString("Ta_TipoCombustible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu Aeronave.
        /// </summary>
        internal static string Ta_Titulo {
            get {
                return ResourceManager.GetString("Ta_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especificaciones.
        /// </summary>
        internal static string Ta_TituloTab1 {
            get {
                return ResourceManager.GetString("Ta_TituloTab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        internal static string Ta_TituloTab2 {
            get {
                return ResourceManager.GetString("Ta_TituloTab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tripulación:.
        /// </summary>
        internal static string Ta_Tripulacion {
            get {
                return ResourceManager.GetString("Ta_Tripulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad Crucero:.
        /// </summary>
        internal static string Ta_VelocidadCrucero {
            get {
                return ResourceManager.GetString("Ta_VelocidadCrucero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar usuario.
        /// </summary>
        internal static string Us_AltaUsuario {
            get {
                return ResourceManager.GetString("Us_AltaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno:.
        /// </summary>
        internal static string Us_ApeMat {
            get {
                return ResourceManager.GetString("Us_ApeMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno:.
        /// </summary>
        internal static string Us_ApePat {
            get {
                return ResourceManager.GetString("Us_ApePat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular:.
        /// </summary>
        internal static string Us_Celular {
            get {
                return ResourceManager.GetString("Us_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma contraseña:.
        /// </summary>
        internal static string Us_ConfirPass {
            get {
                return ResourceManager.GetString("Us_ConfirPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres:.
        /// </summary>
        internal static string Us_Nombre {
            get {
                return ResourceManager.GetString("Us_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string Us_Password {
            get {
                return ResourceManager.GetString("Us_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto:.
        /// </summary>
        internal static string Us_Puesto {
            get {
                return ResourceManager.GetString("Us_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de usuarios.
        /// </summary>
        internal static string Us_SubTituloPagUsuarios {
            get {
                return ResourceManager.GetString("Us_SubTituloPagUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edición de usuarios.
        /// </summary>
        internal static string Us_TituloEdUsuarios {
            get {
                return ResourceManager.GetString("Us_TituloEdUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de Usuarios.
        /// </summary>
        internal static string Us_TituloPagUsuarios {
            get {
                return ResourceManager.GetString("Us_TituloPagUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no son iguales.
        /// </summary>
        internal static string Us_ValConfirPass {
            get {
                return ResourceManager.GetString("Us_ValConfirPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no es válido.
        /// </summary>
        internal static string Us_ValCorreo {
            get {
                return ResourceManager.GetString("Us_ValCorreo", resourceCulture);
            }
        }
    }
}
